[
  { label: "Zeta", name: "in.zeta.android" },
  { label: "YouTube", name: "com.google.android.youtube" },
  { label: "Truecaller", name: "com.truecaller" },
  { label: "Google", name: "com.google.android.googlequicksearchbox" },
  { label: "Telegram", name: "org.telegram.messenger" },
  { label: "DroidEdit Free", name: "com.aor.droidedit" },
  { label: "Airtel", name: "com.myairtelapp" },
  { label: "WhatsApp", name: "com.whatsapp" },
  { label: "File Manager +", name: "com.alphainventor.filemanager" },
  { label: "PicsArt", name: "com.picsart.studio" },
  { label: "Sheets", name: "com.google.android.apps.docs.editors.sheets" },
  { label: "Slides", name: "com.google.android.apps.docs.editors.slides" },
  { label: "Authenticator", name: "com.google.android.apps.authenticator2" },
  { label: "Messages", name: "com.google.android.apps.messaging" },
  { label: "Amazon Shopping", name: "in.amazon.mShop.android.shopping" },
  { label: "Sticker Maker for WhatsApp", name: "stickerwhatsapp.com.stickers" },
  { label: "Splitwise", name: "com.Splitwise.SplitwiseMobile" },
  { label: "Psych!", name: "com.wb.goog.ellen.psych" },
  { label: "Lens", name: "com.google.ar.lens" },
  { label: "Google Play Store", name: "com.android.vending" },
  { label: "PUBG MOBILE", name: "com.tencent.ig" },
  { label: "HDFC Bank", name: "com.snapwork.hdfc" },
  { label: "Airtel Services", name: "com.android.stk" },
  { label: "Camera", name: "com.hmdglobal.camera2" },
  { label: "Clock", name: "com.google.android.deskclock" },
  { label: "Custome Launchar", name: "com.example.customelaunchar" },
  { label: "Device Personalization Services", name: "com.google.android.as" },
  { label: "Gmail", name: "com.google.android.gm" },
  { label: "Duo", name: "com.google.android.apps.tachyon" },
  { label: "OlaCabs", name: "com.olacabs.customer" },
  { label: "Google Play Music", name: "com.google.android.music" },
  { label: "activity_logger_react", name: "com.activity_logger_react" },
  { label: "Digital Wellbeing", name: "com.google.android.apps.wellbeing" },
  { label: "Phone", name: "com.google.android.dialer" },
  { label: "Files", name: "com.google.android.apps.nbu.files" },
  { label: "Adobe Scan", name: "com.adobe.scan.android" },
  { label: "Drive", name: "com.google.android.apps.docs" },
  { label: "Maps", name: "com.google.android.apps.maps" },
  { label: "Mera iMobile", name: "com.csam.icici.bank.mimobile" },
  { label: "Contacts", name: "com.google.android.contacts" },
  { label: "Calculator", name: "com.google.android.calculator" },
  { label: "Chrome", name: "com.android.chrome" },
  { label: "Medium", name: "com.medium.reader" },
  { label: "Google Play Movies", name: "com.google.android.videos" },
  { label: "Boomerang", name: "com.instagram.boomerang" },
  { label: "Photos", name: "com.google.android.apps.photos" },
  { label: "Calendar", name: "com.google.android.calendar" },
  { label: "Miracast Shortcut", name: "com.mattgmg.miracastwidget" },
  { label: "Uber", name: "com.ubercab" },
  { label: "Zomato", name: "com.application.zomato" },
  { label: "JuiceSSH", name: "com.sonelli.juicessh" },
  { label: "Mindly", name: "com.dripgrind.mindly" },
  { label: "BombSquad", name: "net.froemling.bombsquad" },
  { label: "Slack", name: "com.Slack" },
  { label: "Gaana", name: "com.gaana" },
  { label: "Adobe Acrobat", name: "com.adobe.reader" },
  { label: "Gallery Go", name: "com.google.android.apps.photosgo" },
  { label: "LinkedIn", name: "com.linkedin.android" },
  { label: "Settings", name: "com.android.settings" },
  { label: "Google Pay", name: "com.google.android.apps.nbu.paisa.user" },
  { label: "My phone", name: "com.hmdglobal.support" },
  { label: "Myntra", name: "com.myntra.android" },
  { label: "Rapido", name: "com.rapido.passenger" },
  { label: "Bounce", name: "com.metrobikes.app" },
  { label: "Wallpapers", name: "com.google.android.apps.wallpaper" },
  { label: "Keep notes", name: "com.google.android.keep" },
  { label: "FM Radio", name: "com.evenwell.fmradio" },
  { label: "Swiggy", name: "in.swiggy.android" },
  { label: "Slim Launcher", name: "com.sduduzog.slimlauncher" },
  { label: "System Tracing", name: "com.android.traceur" },
  { label: "Google Play Games", name: "com.google.android.play.games" },
  { label: "Google News", name: "com.google.android.apps.magazines" },
  { label: "Voice Recorder", name: "com.media.bestrecorder.audiorecorder" },
  { label: "WPS Office", name: "cn.wps.moffice_eng" },
  { label: "Gallery", name: "com.simplemobiletools.gallery" },
  { label: "Amazon Kindle", name: "com.amazon.kindle" }
];
